/* This script will be executed at the installation of the pack and will create a placeholder for the metrics to be stored */
/* an elasticsearch index will also store the data under the same name if possible */

CREATE TABLE IF NOT EXISTS `metric_basic` (
   `table` TEXT NULL,
   `database` TEXT NULL,
   `dbversion` TEXT NULL,
   `column` TEXT NULL,
   `date` DATE NULL,
   `value_counts` BIGINT NULL,
   `na_values` BIGINT NULL,
   `percent_na_values` FLOAT NULL,
   `data_type` TEXT NULL,
   `infered_data_type` TEXT NULL,
   `levels_count` BIGINT NULL,
   `highest_frequency` BIGINT NULL,
   `sndHighestFrequency` BIGINT NULL,
   `thrdHighestFrequency` BIGINT NULL,
   `ratio_level_frequency` FLOAT NULL,
   `is_key` TINYINT NULL,
   `is_categorical` TINYINT NULL,
   `min_num_var` FLOAT NULL,
   `max_num_var` FLOAT NULL,
   `mean_num_var` FLOAT NULL,
   `median_num_var` FLOAT NULL,
   `std_num_var` FLOAT NULL,
   `delta_value_counts` FLOAT NULL,
   `evol_value_counts` FLOAT NULL,
   `delta_na_values` FLOAT NULL,
   `evol_na_values` FLOAT NULL,
   `delta_percent_na_values` FLOAT NULL,
   `evol_percent_na_values` FLOAT NULL,
   `delta_data_type` FLOAT NULL,
   `evol_data_type` FLOAT NULL,
   `delta_infered_data_type` FLOAT NULL,
   `evol_infered_data_type` FLOAT NULL,
   `delta_levels_count` FLOAT NULL,
   `evol_levels_count` FLOAT NULL,
   `delta_highest_frequency` FLOAT NULL,
   `evol_highest_frequency` FLOAT NULL,
   `delta_sndHighestFrequency` FLOAT NULL,
   `evol_sndHighestFrequency` FLOAT NULL,
   `delta_thrdHighestFrequency` FLOAT NULL,
   `evol_thrdHighestFrequency` FLOAT NULL,
   `delta_ratio_level_frequency` FLOAT NULL,
   `evol_ratio_level_frequency` FLOAT NULL,
   `delta_is_key` FLOAT NULL,
   `evol_is_key` FLOAT NULL,
   `delta_is_categorical` FLOAT NULL,
   `evol_is_categorical` FLOAT NULL,
   `delta_min_num_var` FLOAT NULL,
   `evol_min_num_var` FLOAT NULL,
   `delta_max_num_var` FLOAT NULL,
   `evol_max_num_var` FLOAT NULL,
   `delta_mean_num_var` FLOAT NULL,
   `evol_mean_num_var` FLOAT NULL,
   `delta_median_num_var` FLOAT NULL,
   `evol_median_num_var` FLOAT NULL,
   `delta_std_num_var` FLOAT NULL,
   `evol_std_num_var` FLOAT NULL
);

CREATE TABLE IF NOT EXISTS `metric_basic_levels` (
   `table` TEXT NULL,
   `database` TEXT NULL,
   `dbversion` TEXT NULL,
   `column` TEXT NULL,
   `date` DATE NULL,
   `value` TEXT NULL,
   `frequency` FLOAT NULL,
   `delta_frequency` FLOAT NULL,
   `evol_frequency` FLOAT NULL)